### ISSUE TITLE
Ace editor has no height

### ISSUE THREAD

**Issue by xaviergmail** [procourse/procourse-static-pages#6]
Originally:
===
![original](https://xavie.ru/i/17ZwIkR.png)
After manually setting height:
===
![manually setting height](https://xavie.ru/i/17SLht9.png)

**Comment by joebuhlig** [comment]
Give this an update and let me know if the issue remains. I think I have it resolved in the midst of the rename migration.

**Comment by xaviergmail** [comment]
Works wonders. Thank you! :)
